{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "print-operator.serviceAccountName" . }}
  labels:
{{ include "print-operator.labels" . | nindent 4 }}
{{- end -}}
